spring.application.name=SBA301_2026Spring_Lab02
server.servlet.context-path=/
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TestDB;encrypt=false;
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.data.jpa.repositories.enabled=true
server.port=8080
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true